import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { isAbsolute, join } from 'node:path'
import { after, describe, it } from 'node:test'
import { fileURLToPath, pathToFileURL } from 'node:url'
import type { SkillRegistrationLike, SkillsLike } from '../../src/host-services.ts'
import { SKILL_NAME } from '../../src/shared.ts'
import { SKILL_SOURCE } from '../../src/skill.generated.ts'
import { bundledSkillPath, registerOrchestrationSkill, skillRegistration } from '../../src/skill.ts'

const root = fileURLToPath(new URL('../../', import.meta.url))
const script = join(root, 'scripts', 'gen-skill.mjs')
const skillFile = join(root, 'skills', 'orchestrate-subagents', 'SKILL.md')
// The real path: a module imported from here reports it (a temp directory is often a symlink, as `/var` is on macOS).
const scratch = realpathSync(mkdtempSync(join(tmpdir(), 'orq-skill-')))
// The scratch directory holds generated `.ts` modules the tests import: give it its own ES module scope.
writeFileSync(join(scratch, 'package.json'), '{ "type": "module" }')
after(() => { rmSync(scratch, { recursive: true, force: true }) })

/** The generated module, widened so the tests type-check whether or not the Markdown carries `when-to-use`. */
const real: { readonly name: string; readonly description: string; readonly whenToUse?: string; readonly content: string } = SKILL_SOURCE

/** Run the generator the way a developer does: through its command line. */
function generate(args: readonly string[], cwd = root): { readonly status: number | null; readonly stdout: string; readonly stderr: string } {
  const { status, stdout, stderr } = spawnSync(process.execPath, [script, ...args], { cwd, encoding: 'utf8' })
  return { status, stdout, stderr }
}

let fixtures = 0
/** Write a SKILL.md fixture; every call gets a fresh pair of file names, so an imported module is never a stale cached one. */
function fixture(markdown: string): { readonly source: string; readonly out: string } {
  fixtures += 1
  const source = join(scratch, `skill-${String(fixtures)}.md`)
  writeFileSync(source, markdown)
  return { source, out: join(scratch, `skill-${String(fixtures)}.generated.ts`) }
}

/** Generate a module from Markdown and import what it exports. */
async function generated(markdown: string): Promise<Readonly<Record<string, unknown>>> {
  const { source, out } = fixture(markdown)
  const result = generate(['--source', source, '--out', out])
  assert.equal(result.status, 0, result.stderr)
  return ((await import(pathToFileURL(out).href)) as { SKILL_SOURCE: Readonly<Record<string, unknown>> }).SKILL_SOURCE
}

/** A SKILL.md: frontmatter lines, then the body lines. */
function markdown(frontmatter: readonly string[], ...body: readonly string[]): string {
  return ['---', ...frontmatter, '---', ...body].join('\n')
}

describe('the generated module', () => {
  it('is current: gen-skill --check agrees with src/skill.generated.ts', () => {
    const result = generate(['--check'])
    assert.equal(result.status, 0, result.stderr)
    assert.equal(result.stdout.trim(), 'gen-skill: up to date')
  })

  it('is found from any working directory: the defaults resolve against the repository root', () => {
    const result = generate(['--check'], scratch)
    assert.equal(result.status, 0, result.stderr)
    assert.equal(result.stdout.trim(), 'gen-skill: up to date')
  })

  it('names the repository-relative Markdown it came from and ends in one newline', () => {
    const text = readFileSync(join(root, 'src', 'skill.generated.ts'), 'utf8')
    assert.ok(text.startsWith(
      '/**\n * GENERATED by scripts/gen-skill.mjs from skills/orchestrate-subagents/SKILL.md. Do not edit by hand:\n'
      + ' * edit the Markdown and run `node scripts/gen-skill.mjs`.\n */\nexport const SKILL_SOURCE = {\n',
    ))
    assert.ok(text.endsWith('\n} as const\n'))
  })
})

describe('scripts/gen-skill.mjs', () => {
  const full = markdown(
    ['name: demo-skill', 'description: Does the demo: the first colon splits, the rest stays', 'when-to-use: When someone asks for a demo'],
    '',
    '# Demo',
    '',
    'Body text.',
    '',
  )

  it('reads name, description and when-to-use from the frontmatter and the body from after it', async () => {
    assert.deepEqual(await generated(full), {
      name: 'demo-skill',
      description: 'Does the demo: the first colon splits, the rest stays',
      whenToUse: 'When someone asks for a demo',
      content: '# Demo\n\nBody text.',
    })
  })

  it('writes `wrote <out>` and a module with JSON string literals in a fixed order', () => {
    const { source, out } = fixture(full)
    const result = generate(['--source', source, '--out', out])
    assert.equal(result.status, 0, result.stderr)
    assert.match(result.stdout, /^gen-skill: wrote .*skill-\d+\.generated\.ts\n$/)
    const [open, from, hint, close, ...rest] = readFileSync(out, 'utf8').split('\n')
    assert.equal(open, '/**')
    assert.match(from ?? '', /^ \* GENERATED by scripts\/gen-skill\.mjs from .*skill-\d+\.md\. Do not edit by hand:$/)
    assert.equal(hint, ' * edit the Markdown and run `node scripts/gen-skill.mjs`.')
    assert.equal(close, ' */')
    assert.deepEqual(rest, [
      'export const SKILL_SOURCE = {',
      '  name: "demo-skill",',
      '  description: "Does the demo: the first colon splits, the rest stays",',
      '  whenToUse: "When someone asks for a demo",',
      '  content: "# Demo\\n\\nBody text.",',
      '} as const',
      '',
    ])
  })

  it('leaves whenToUse out when the frontmatter has no when-to-use, or an empty one', async () => {
    assert.deepEqual(await generated(markdown(['name: demo', 'description: d'], 'Body')), { name: 'demo', description: 'd', content: 'Body' })
    assert.deepEqual(await generated(markdown(['name: demo', 'description: d', 'when-to-use:'], 'Body')), { name: 'demo', description: 'd', content: 'Body' })
  })

  it('strips one pair of matching quotes and nothing else', async () => {
    assert.deepEqual(await generated(markdown(['name: "quoted-name"', "description: 'single: quoted'", 'when-to-use: "unbalanced\''], 'Body')), {
      name: 'quoted-name',
      description: 'single: quoted',
      whenToUse: '"unbalanced\'',
      content: 'Body',
    })
    assert.deepEqual(await generated(markdown(['name: demo', 'description: ""inner""'], 'Body')), { name: 'demo', description: '"inner"', content: 'Body' })
  })

  it('accepts any character inside a value, even the line separators a JavaScript regex treats as a line end', async () => {
    const skill = await generated(markdown(['name: demo', 'description: before\u2028between\u2029after, with `backticks` and ${braces}'], 'Body'))
    assert.equal(skill['description'], 'before\u2028between\u2029after, with `backticks` and ${braces}')
  })

  it('normalizes CRLF line endings in the frontmatter and in the body', async () => {
    const crlf = await generated(full.replaceAll('\n', '\r\n'))
    assert.deepEqual(crlf, await generated(full))
    assert.equal(String(crlf['content']).includes('\r'), false)
  })

  it('drops the blank lines before the body and the whitespace after it, and keeps the rest as written', async () => {
    const skill = await generated(markdown(['name: demo', 'description: d'], '', '  ', '\t', '    indented first line', '', '', 'last line   ', '', '   ', ''))
    assert.equal(skill['content'], '    indented first line\n\n\nlast line')
  })

  it('does not cut the body at a later `---` line (a horizontal rule)', async () => {
    const skill = await generated(markdown(['name: demo', 'description: d'], 'above', '', '---', '', 'below'))
    assert.equal(skill['content'], 'above\n\n---\n\nbelow')
  })

  it('ignores the keys it does not know, comments, blank lines and the nested block of an ignored key', async () => {
    const skill = await generated(markdown([
      '# a comment', 'license: MIT', '', 'metadata:', '  author: someone', '  tags:', '    - a', 'name: demo', 'description: d', 'allowed-tools: Bash',
    ], 'Body'))
    assert.deepEqual(skill, { name: 'demo', description: 'd', content: 'Body' })
  })

  it('is deterministic: the same Markdown gives the same bytes, from any working directory', () => {
    const { source, out } = fixture(full)
    assert.equal(generate(['--source', source, '--out', out]).status, 0)
    const first = readFileSync(out)
    assert.equal(generate(['--source', source, '--out', out], scratch).status, 0)
    assert.deepEqual(readFileSync(out), first)
  })

  describe('rejects a source it cannot trust, with a message and no output file', () => {
    const cases: readonly (readonly [title: string, text: string, message: RegExp])[] = [
      ['no frontmatter', '# Just a body\n', /no frontmatter/],
      ['an empty file', '', /no frontmatter/],
      ['a frontmatter that is never closed', '---\nname: demo\ndescription: d\n', /not closed/],
      ['a missing name', markdown(['description: d'], 'Body'), /needs a non-empty "name"/],
      ['an empty name', markdown(['name:', 'description: d'], 'Body'), /needs a non-empty "name"/],
      ['a missing description', markdown(['name: demo'], 'Body'), /needs a non-empty "description"/],
      ['an empty quoted description', markdown(['name: demo', 'description: ""'], 'Body'), /needs a non-empty "description"/],
      ['a description that continues on an indented line', markdown(['name: demo', 'description: first line', '  second line'], 'Body'), /"description" spans several lines/],
      ['a continuation line that looks like a key', markdown(['name: demo', 'description: first line', '  second: line'], 'Body'), /"description" spans several lines/],
      ['a description that starts on the next line', markdown(['name: demo', 'description:', '  starts below'], 'Body'), /"description" spans several lines/],
      ['a folded description', markdown(['name: demo', 'description: >', '  folded'], 'Body'), /block scalar/],
      ['a literal description', markdown(['name: demo', 'description: |-', '  literal'], 'Body'), /block scalar/],
      ['a when-to-use that continues on an indented line', markdown(['name: demo', 'description: d', 'when-to-use: first', '  second'], 'Body'), /"when-to-use" spans several lines/],
      ['a continuation line that is not a key', markdown(['name: demo', 'description: first line', 'second line'], 'Body'), /expected "key: value"/],
      ['a key set twice', markdown(['name: demo', 'name: other', 'description: d'], 'Body'), /"name" is set twice/],
    ]
    for (const [title, text, message] of cases) {
      it(title, () => {
        const { source, out } = fixture(text)
        const result = generate(['--source', source, '--out', out])
        assert.equal(result.status, 1)
        assert.match(result.stderr, /^gen-skill: /)
        assert.match(result.stderr, message)
        assert.equal(result.stdout, '')
        assert.equal(existsSync(out), false)
      })
    }

    it('names the line of the problem', () => {
      const { source, out } = fixture(markdown(['name: demo', 'description: first line', '  second line'], 'Body'))
      assert.match(generate(['--source', source, '--out', out]).stderr, /skill-\d+\.md:4: /)
    })

    it('a source that does not exist', () => {
      const result = generate(['--source', join(scratch, 'nothing-here.md'), '--out', join(scratch, 'nothing-here.ts')])
      assert.equal(result.status, 1)
      assert.match(result.stderr, /^gen-skill: cannot read .*nothing-here\.md/)
    })
  })

  describe('--check', () => {
    it('fails with exit 1 when there is no output file yet, and never writes one', () => {
      const { source, out } = fixture(full)
      const result = generate(['--source', source, '--out', out, '--check'])
      assert.equal(result.status, 1)
      assert.match(result.stderr, /^gen-skill: .*skill-\d+\.generated\.ts is out of date: run node scripts\/gen-skill\.mjs\n$/)
      assert.equal(result.stdout, '')
      assert.equal(existsSync(out), false)
    })

    it('passes on a fresh output and fails (exit 1) once the Markdown or the file moved on, without touching the file', () => {
      const { source, out } = fixture(full)
      assert.equal(generate(['--source', source, '--out', out]).status, 0)
      const current = generate(['--source', source, '--out', out, '--check'])
      assert.equal(current.status, 0)
      assert.equal(current.stdout.trim(), 'gen-skill: up to date')

      const fresh = readFileSync(out, 'utf8')
      writeFileSync(source, full.replace('When someone asks for a demo', 'Whenever'))
      const stale = generate(['--source', source, '--out', out, '--check'])
      assert.equal(stale.status, 1)
      assert.match(stale.stderr, /is out of date: run node scripts\/gen-skill\.mjs/)
      assert.equal(readFileSync(out, 'utf8'), fresh)

      assert.equal(generate(['--source', source, '--out', out]).status, 0)
      assert.equal(generate(['--source', source, '--out', out, '--check']).status, 0)
      writeFileSync(out, `${readFileSync(out, 'utf8')}// edited by hand\n`)
      assert.equal(generate(['--source', source, '--out', out, '--check']).status, 1)
    })

    it('still reports a source it cannot read, as the error it is', () => {
      const { source, out } = fixture('# no frontmatter\n')
      const result = generate(['--source', source, '--out', out, '--check'])
      assert.equal(result.status, 1)
      assert.match(result.stderr, /no frontmatter/)
    })
  })

  it('exits 2 with the usage on a bad command line', () => {
    for (const args of [['--bogus'], ['--source'], ['--out'], ['positional.md']]) {
      const result = generate(args)
      assert.equal(result.status, 2, args.join(' '))
      assert.match(result.stderr, /usage: node scripts\/gen-skill\.mjs/)
    }
  })
})

describe('the skill the plugin ships', () => {
  it('is named like the constant the browser half and the dialog use, in the grammar DSH accepts', () => {
    assert.equal(real.name, SKILL_NAME)
    assert.match(real.name, /^[a-z0-9]+(?:-[a-z0-9]+)*$/)
  })

  it('has a description that fits the 500 characters DSH keeps in the model\'s catalog, in one line', () => {
    assert.ok(real.description.length >= 40, `${String(real.description.length)} characters`)
    assert.ok(real.description.length <= 500, `${String(real.description.length)} characters`)
    assert.equal(/[\r\n]/.test(real.description), false)
  })

  it('carries the instructions, without the frontmatter, normalized', () => {
    assert.ok(real.content.length > 1500, `${String(real.content.length)} characters`)
    for (const phrase of ['Do not read code yourself', 'verifier', 'parallel', 'Reading by delegation']) {
      assert.ok(real.content.includes(phrase), `the skill text has no "${phrase}"`)
    }
    assert.equal(real.content.startsWith('---'), false)
    assert.equal(real.content.includes('\r'), false)
    assert.equal(real.content, real.content.trim())
  })

  it('is the text of the Markdown file DSH is shown as the skill\'s path', () => {
    assert.ok(readFileSync(skillFile, 'utf8').replaceAll('\r\n', '\n').includes(real.content))
  })

  it('is a /name token DSH\'s gesture matcher recognizes, at the start of a message and inside one', () => {
    // A copy of SKILL_GESTURE from DSH 0.1.6-alpha.2 (packages/skill/tool-skill/src/index.ts); this suite has no DSH checkout to read it from.
    const gesture = /(^|\s)\/([a-z0-9]+(?:-[a-z0-9]+)*)(?=\s|$)/g
    const tokens = (text: string): string[] => [...text.matchAll(gesture)].map(match => match[2] ?? '')
    assert.deepEqual(tokens(`/${SKILL_NAME}`), [SKILL_NAME])
    assert.deepEqual(tokens(`/${SKILL_NAME} fix the login bug`), [SKILL_NAME])
    assert.deepEqual(tokens(`fix the login bug /${SKILL_NAME}`), [SKILL_NAME])
    assert.deepEqual(tokens(`see /usr/${SKILL_NAME} and 5/8`), [])
  })
})

describe('skillRegistration', () => {
  it('describes the skill to DSH: its text, this plugin as the source, user-invocable always', () => {
    const registration = skillRegistration({ modelInvocable: true })
    assert.deepEqual(registration, {
      name: real.name,
      description: real.description,
      content: real.content,
      source: 'dsh-orquestrator',
      invocation: { modelInvocable: true, userInvocable: true },
      ...real.whenToUse === undefined ? {} : { whenToUse: real.whenToUse },
    })
  })

  it('takes modelInvocable from the settings and stays user-invocable either way', () => {
    assert.deepEqual(skillRegistration({ modelInvocable: false }).invocation, { modelInvocable: false, userInvocable: true })
    assert.deepEqual(skillRegistration({ modelInvocable: true }).invocation, { modelInvocable: true, userInvocable: true })
  })

  it('has a path only when given one', () => {
    assert.equal('path' in skillRegistration({ modelInvocable: true }), false)
    assert.equal(skillRegistration({ modelInvocable: true }, '/pkg/skills/orchestrate-subagents/SKILL.md').path, '/pkg/skills/orchestrate-subagents/SKILL.md')
  })

  it('never sets resourceBase: DSH would tell the model to read files from a directory, which the skill forbids', () => {
    assert.equal('resourceBase' in skillRegistration({ modelInvocable: true }), false)
    assert.equal('resourceBase' in skillRegistration({ modelInvocable: false }, skillFile), false)
  })
})

describe('bundledSkillPath', () => {
  it('finds the Markdown file next to src/, as an existing absolute path', () => {
    const path = bundledSkillPath()
    assert.ok(path !== undefined)
    assert.ok(isAbsolute(path))
    assert.ok(existsSync(path))
    assert.ok(path.endsWith(join('skills', 'orchestrate-subagents', 'SKILL.md')))
    assert.equal(path, skillFile)
  })

  it('is the same relative URL from the bundled lib/, a sibling of skills/ under the package root', () => {
    const fromLib = new URL('../skills/orchestrate-subagents/SKILL.md', pathToFileURL(join(root, 'lib', 'index.js')))
    assert.equal(fileURLToPath(fromLib), skillFile)
  })

  it('answers undefined, never an error, where the package has no skills/ directory', async () => {
    // A copy of the module in a package that lacks the file, as a build that left `skills/` out would be.
    const pkg = join(scratch, 'pkg-without-skills')
    mkdirSync(join(pkg, 'src'), { recursive: true })
    for (const file of ['skill.ts', 'skill.generated.ts', 'host-services.ts']) copyFileSync(join(root, 'src', file), join(pkg, 'src', file))
    const copy = await import(pathToFileURL(join(pkg, 'src', 'skill.ts')).href) as typeof import('../../src/skill.ts')
    assert.equal(copy.bundledSkillPath(), undefined)

    const registered: SkillRegistrationLike[] = []
    const skills: SkillsLike = { register(skill) { registered.push(skill); return () => undefined } }
    assert.equal(copy.registerOrchestrationSkill(skills, { modelInvocable: true }, { info: () => undefined, warn: () => undefined }).available, true)
    assert.equal(registered.length, 1)
    assert.equal('path' in (registered[0] ?? {}), false)

    mkdirSync(join(pkg, 'skills', 'orchestrate-subagents'), { recursive: true })
    writeFileSync(join(pkg, 'skills', 'orchestrate-subagents', 'SKILL.md'), '# here now\n')
    assert.equal(copy.bundledSkillPath(), join(pkg, 'skills', 'orchestrate-subagents', 'SKILL.md'))
  })
})

/** A registry double that records what it is given and counts the disposals. */
interface FakeRegistry {
  readonly skills: SkillsLike
  readonly registered: SkillRegistrationLike[]
  disposals: number
}

/**
 * A registry double. With no failure it applies the rules of DSH 0.1.6-alpha.2's `validateRuntimeSkill` (a copy of
 * packages/skill/skill/src/index.ts), so that a registration DSH would refuse fails here too; with a failure it throws it.
 */
function fakeRegistry(failure?: unknown): FakeRegistry {
  const fake: FakeRegistry = {
    registered: [],
    disposals: 0,
    skills: {
      register(skill) {
        if (failure !== undefined) throw failure
        if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(skill.name)) throw new Error(`invalid skill name "${skill.name}"`)
        if (skill.description.length === 0) throw new Error(`skill "${skill.name}" requires a description`)
        if (typeof skill.invocation?.modelInvocable !== 'boolean' || typeof skill.invocation.userInvocable !== 'boolean') throw new TypeError('invocation policy')
        if (typeof skill.content !== 'string' || typeof skill.source !== 'string') throw new TypeError('content and source must be strings')
        if (skill.path !== undefined && typeof skill.path !== 'string') throw new TypeError('path must be a string')
        fake.registered.push(skill)
        return () => { fake.disposals += 1 }
      },
    },
  }
  return fake
}

/** A logger double. */
function fakeLogger(): { readonly logger: { info(message: string): void; warn(message: string): void }; readonly info: string[]; readonly warn: string[] } {
  const info: string[] = []
  const warn: string[] = []
  return { logger: { info: message => { info.push(message) }, warn: message => { warn.push(message) } }, info, warn }
}

describe('registerOrchestrationSkill', () => {
  it('registers the skill once, with its text, its path and the operator\'s invocation choice, and says so', () => {
    const registry = fakeRegistry()
    const log = fakeLogger()
    const handle = registerOrchestrationSkill(registry.skills, { modelInvocable: true }, log.logger)
    assert.equal(handle.available, true)
    assert.equal(registry.registered.length, 1)
    assert.deepEqual(registry.registered[0], skillRegistration({ modelInvocable: true }, skillFile))
    assert.equal(registry.registered[0]?.name, SKILL_NAME)
    assert.equal('resourceBase' in (registry.registered[0] ?? {}), false)
    assert.deepEqual(log.info, ['dsh-orquestrator: registered the global skill "orchestrate-subagents" (model-invocable: yes)'])
    assert.deepEqual(log.warn, [])
    assert.equal(registry.disposals, 0)
  })

  it('keeps the skill out of the model\'s catalog when the operator says so, and the log says no', () => {
    const registry = fakeRegistry()
    const log = fakeLogger()
    registerOrchestrationSkill(registry.skills, { modelInvocable: false }, log.logger)
    assert.deepEqual(registry.registered[0]?.invocation, { modelInvocable: false, userInvocable: true })
    assert.deepEqual(log.info, ['dsh-orquestrator: registered the global skill "orchestrate-subagents" (model-invocable: no)'])
  })

  it('unregisters through the registry\'s disposer, once, however often dispose is called', () => {
    const registry = fakeRegistry()
    const handle = registerOrchestrationSkill(registry.skills, { modelInvocable: true }, fakeLogger().logger)
    handle.dispose()
    handle.dispose()
    assert.equal(registry.disposals, 1)
  })

  it('answers unavailable, with a warning and no error, when the registry refuses the skill', () => {
    const registry = fakeRegistry(new Error('a skill named "orchestrate-subagents" is reserved'))
    const log = fakeLogger()
    const handle = registerOrchestrationSkill(registry.skills, { modelInvocable: true }, log.logger)
    assert.equal(handle.available, false)
    assert.deepEqual(log.warn, ['dsh-orquestrator: could not register the global skill "orchestrate-subagents": a skill named "orchestrate-subagents" is reserved; the dialog will not offer it'])
    assert.deepEqual(log.info, [])
    assert.equal(registry.registered.length, 0)
    assert.doesNotThrow(() => { handle.dispose(); handle.dispose() })
    assert.equal(registry.disposals, 0)
  })

  it('reports whatever was thrown, an Error or not', () => {
    const log = fakeLogger()
    assert.equal(registerOrchestrationSkill(fakeRegistry('plain text').skills, { modelInvocable: true }, log.logger).available, false)
    assert.match(log.warn[0] ?? '', /: plain text; the dialog will not offer it$/)
  })

  it('does not throw when there is no registry to register with', () => {
    const log = fakeLogger()
    const handle = registerOrchestrationSkill(undefined as unknown as SkillsLike, { modelInvocable: true }, log.logger)
    assert.equal(handle.available, false)
    assert.equal(log.warn.length, 1)
  })

  it('registers what a registry that checks like DSH\'s accepts, with a description inside the catalog\'s limit', () => {
    const registry = fakeRegistry()
    assert.equal(registerOrchestrationSkill(registry.skills, { modelInvocable: true }, fakeLogger().logger).available, true)
    assert.ok((registry.registered[0]?.description.length ?? 0) <= 500)
  })
})
